AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Errors Service Stack

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 300
        MemorySize: 512
        Runtime: go1.x
        Environment:
          Variables:
            ENV: !Ref Env
        Tags:
          Company: Ringoid
          Service: errors
          Environment: !Ref Env

Resources:

  ErrorsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref AWS::StackName
      StageName: Prod

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ErrorsApiProdStage
    Properties:
      BasePath: errors
      DomainName:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, APIDomainNameExport] ]
      RestApiId: !Ref ErrorsApi
      Stage: Prod

  TimeoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, timeout] ]
      Handler: timeout
      CodeUri: ./timeout.zip
      Description: Timeout function
      Events:
        TimeoutEvent:
          Type: Api
          Properties:
            Path: /timeout
            Method: post
            RestApiId: !Ref ErrorsApi

  InvalidTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, invalidtoken] ]
      Handler: invalidtoken
      CodeUri: ./invalidtoken.zip
      Description: InvalidToken function
      Events:
        TimeoutEvent:
          Type: Api
          Properties:
            Path: /invalidtoken
            Method: post
            RestApiId: !Ref ErrorsApi

  NonOkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, nonok] ]
      Handler: nonok
      CodeUri: ./nonok.zip
      Description: Nonok function
      Events:
        TimeoutEvent:
          Type: Api
          Properties:
            Path: /nonok
            Method: post
            RestApiId: !Ref ErrorsApi

  OldVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, old_version] ]
      Handler: old
      CodeUri: ./old.zip
      Description: Old function
      Events:
        TimeoutEvent:
          Type: Api
          Properties:
            Path: /old_version
            Method: post
            RestApiId: !Ref ErrorsApi

  InternalServerErrorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, internalerror] ]
      Handler: internalerror
      CodeUri: ./internalerror.zip
      Description: InternalServerError function
      Events:
        TimeoutEvent:
          Type: Api
          Properties:
            Path: /internalerror
            Method: post
            RestApiId: !Ref ErrorsApi
